export interface CommonFoodItem {
  id: string
  name: string
  category: 'Frutas' | 'Proteínas' | 'Carbohidratos' | 'Lácteos' | 'Grasas & Frutos Secos' | 'Verduras'
  emoji: string
  defaultServingG: number
  defaultServingName: string
  calories: number // per 100g
  protein: number // per 100g
  carbs: number // per 100g
  fat: number // per 100g
  fiber?: number // per 100g
  tags?: string[]
}

export const COMMON_FOOD_CATEGORIES = [
  'Todas',
  'Frutas',
  'Proteínas',
  'Carbohidratos',
  'Lácteos',
  'Grasas & Frutos Secos',
  'Verduras',
] as const

export type CommonFoodCategory = (typeof COMMON_FOOD_CATEGORIES)[number]

export const COMMON_FOODS_DATABASE: CommonFoodItem[] = [
  // ── FRUTAS ──
  {
    id: 'f-platano',
    name: 'Plátano / Banana',
    category: 'Frutas',
    emoji: '🍌',
    defaultServingG: 120,
    defaultServingName: '1 pieza mediana (120g)',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    tags: ['banana', 'fruta', 'potasio'],
  },
  {
    id: 'f-manzana',
    name: 'Manzana',
    category: 'Frutas',
    emoji: '🍎',
    defaultServingG: 150,
    defaultServingName: '1 pieza mediana (150g)',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    tags: ['manzana', 'fruta', 'fibra'],
  },
  {
    id: 'f-kiwi',
    name: 'Kiwi',
    category: 'Frutas',
    emoji: '🥝',
    defaultServingG: 80,
    defaultServingName: '1 unidad (80g)',
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3.0,
    tags: ['kiwi', 'vitamina c'],
  },
  {
    id: 'f-naranja',
    name: 'Naranja',
    category: 'Frutas',
    emoji: '🍊',
    defaultServingG: 180,
    defaultServingName: '1 pieza (180g)',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    tags: ['naranja', 'citrico'],
  },
  {
    id: 'f-fresas',
    name: 'Fresas / Frutillas',
    category: 'Frutas',
    emoji: '🍓',
    defaultServingG: 150,
    defaultServingName: '1 tazón (150g)',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    tags: ['fresas', 'frutos rojos', 'bajas calorias'],
  },
  {
    id: 'f-arandanos',
    name: 'Arándanos',
    category: 'Frutas',
    emoji: '🫐',
    defaultServingG: 100,
    defaultServingName: '1 puñado (100g)',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    tags: ['arandanos', 'antioxidantes'],
  },
  {
    id: 'f-aguacate',
    name: 'Aguacate / Palta',
    category: 'Frutas',
    emoji: '🥑',
    defaultServingG: 100,
    defaultServingName: '1/2 unidad (100g)',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    tags: ['aguacate', 'palta', 'grasas saludables'],
  },
  {
    id: 'f-sandia',
    name: 'Sandía',
    category: 'Frutas',
    emoji: '🍉',
    defaultServingG: 250,
    defaultServingName: '1 rodaja (250g)',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    tags: ['sandia', 'hidratacion'],
  },
  {
    id: 'f-melon',
    name: 'Melón',
    category: 'Frutas',
    emoji: '🍈',
    defaultServingG: 200,
    defaultServingName: '1 rodaja (200g)',
    calories: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
    fiber: 0.9,
    tags: ['melon', 'fruta'],
  },
  {
    id: 'f-uvas',
    name: 'Uvas',
    category: 'Frutas',
    emoji: '🍇',
    defaultServingG: 120,
    defaultServingName: '1 racimo pequeño (120g)',
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    tags: ['uvas', 'fruta'],
  },
  {
    id: 'f-pera',
    name: 'Pera',
    category: 'Frutas',
    emoji: '🍐',
    defaultServingG: 160,
    defaultServingName: '1 pieza mediana (160g)',
    calories: 57,
    protein: 0.4,
    carbs: 15.2,
    fat: 0.1,
    fiber: 3.1,
    tags: ['pera', 'fibra'],
  },
  {
    id: 'f-mango',
    name: 'Mango',
    category: 'Frutas',
    emoji: '🥭',
    defaultServingG: 150,
    defaultServingName: '1 taza en trozos (150g)',
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    fiber: 1.6,
    tags: ['mango', 'tropical'],
  },
  {
    id: 'f-pina',
    name: 'Piña / Ananá',
    category: 'Frutas',
    emoji: '🍍',
    defaultServingG: 150,
    defaultServingName: '2 rodajas (150g)',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    tags: ['piña', 'anana', 'digestiva'],
  },

  // ── PROTEÍNAS / CARNES / PESCADOS / HUEVOS ──
  {
    id: 'p-pollo',
    name: 'Pechuga de Pollo a la Plancha',
    category: 'Proteínas',
    emoji: '🍗',
    defaultServingG: 150,
    defaultServingName: '1 filete mediano (150g)',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    tags: ['pollo', 'pechuga', 'magra', 'proteina pura'],
  },
  {
    id: 'p-pavo',
    name: 'Pechuga de Pavo',
    category: 'Proteínas',
    emoji: '🦃',
    defaultServingG: 150,
    defaultServingName: '1 filete (150g)',
    calories: 135,
    protein: 30.0,
    carbs: 0.0,
    fat: 1.5,
    tags: ['pavo', 'magra'],
  },
  {
    id: 'p-huevo-entero',
    name: 'Huevo Entero Cocido / Plancha',
    category: 'Proteínas',
    emoji: '🥚',
    defaultServingG: 120,
    defaultServingName: '2 unidades (120g)',
    calories: 155,
    protein: 13.0,
    carbs: 1.1,
    fat: 11.0,
    tags: ['huevo', 'huevos', 'grasas buenas'],
  },
  {
    id: 'p-claras',
    name: 'Claras de Huevo',
    category: 'Proteínas',
    emoji: '🍳',
    defaultServingG: 150,
    defaultServingName: '150ml / 4 claras (150g)',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    tags: ['claras', 'proteina pura', 'sin grasa'],
  },
  {
    id: 'p-ternera',
    name: 'Ternera Magra / Bistec',
    category: 'Proteínas',
    emoji: '🥩',
    defaultServingG: 150,
    defaultServingName: '1 filete (150g)',
    calories: 180,
    protein: 26.0,
    carbs: 0.0,
    fat: 8.5,
    tags: ['ternera', 'carne roja', 'hierro'],
  },
  {
    id: 'p-lomo-cerdo',
    name: 'Lomo de Cerdo Magro',
    category: 'Proteínas',
    emoji: '🥓',
    defaultServingG: 150,
    defaultServingName: '1 filete (150g)',
    calories: 145,
    protein: 28.0,
    carbs: 0.0,
    fat: 3.5,
    tags: ['lomo', 'cerdo', 'magro'],
  },
  {
    id: 'p-salmon',
    name: 'Salmón a la Plancha / Horno',
    category: 'Proteínas',
    emoji: '🐟',
    defaultServingG: 150,
    defaultServingName: '1 lomo (150g)',
    calories: 208,
    protein: 22.0,
    carbs: 0.0,
    fat: 13.0,
    tags: ['salmon', 'pescado azul', 'omega 3'],
  },
  {
    id: 'p-atun-lata',
    name: 'Atún al Natural en Lata',
    category: 'Proteínas',
    emoji: '🥫',
    defaultServingG: 80,
    defaultServingName: '1 lata escurrida (80g)',
    calories: 116,
    protein: 26.0,
    carbs: 0.0,
    fat: 1.0,
    tags: ['atun', 'lata', 'rapido'],
  },
  {
    id: 'p-merluza',
    name: 'Merluza / Pescado Blanco',
    category: 'Proteínas',
    emoji: '🐠',
    defaultServingG: 150,
    defaultServingName: '1 filete (150g)',
    calories: 90,
    protein: 19.0,
    carbs: 0.0,
    fat: 1.5,
    tags: ['merluza', 'pescado blanco', 'ligero'],
  },
  {
    id: 'p-whey',
    name: 'Proteína Whey (Suero)',
    category: 'Proteínas',
    emoji: '🥤',
    defaultServingG: 30,
    defaultServingName: '1 cazo / scoop (30g)',
    calories: 390,
    protein: 78.0,
    carbs: 6.0,
    fat: 5.0,
    tags: ['whey', 'suplemento', 'batido', 'proteina'],
  },
  {
    id: 'p-tofu',
    name: 'Tofu Firme',
    category: 'Proteínas',
    emoji: '🧊',
    defaultServingG: 150,
    defaultServingName: '1 bloque mediano (150g)',
    calories: 120,
    protein: 12.0,
    carbs: 2.0,
    fat: 7.0,
    tags: ['tofu', 'vegano', 'soja'],
  },
  {
    id: 'p-gambas',
    name: 'Gambas / Langostinos Cocidos',
    category: 'Proteínas',
    emoji: '🦐',
    defaultServingG: 100,
    defaultServingName: '1 porción (100g)',
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    tags: ['gambas', 'marisco', 'alta proteina'],
  },
  {
    id: 'p-jamon-serrano',
    name: 'Jamón Serrano / Ibérico Magro',
    category: 'Proteínas',
    emoji: '🍖',
    defaultServingG: 50,
    defaultServingName: '3 lonchas (50g)',
    calories: 220,
    protein: 30.0,
    carbs: 0.5,
    fat: 11.0,
    tags: ['jamon', 'embutido'],
  },

  // ── CARBOHIDRATOS Y GRANOS ──
  {
    id: 'c-arroz-blanco',
    name: 'Arroz Blanco Cocido',
    category: 'Carbohidratos',
    emoji: '🍚',
    defaultServingG: 150,
    defaultServingName: '1 ración cocida (150g)',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    tags: ['arroz', 'carbohidrato', 'energia'],
  },
  {
    id: 'c-arroz-integral',
    name: 'Arroz Integral Cocido',
    category: 'Carbohidratos',
    emoji: '🌾',
    defaultServingG: 150,
    defaultServingName: '1 ración cocida (150g)',
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    fiber: 1.8,
    tags: ['arroz integral', 'fibra'],
  },
  {
    id: 'c-pasta-cocida',
    name: 'Pasta / Fideos Cocidos',
    category: 'Carbohidratos',
    emoji: '🍝',
    defaultServingG: 150,
    defaultServingName: '1 plato cocido (150g)',
    calories: 140,
    protein: 5.0,
    carbs: 28.0,
    fat: 0.6,
    fiber: 1.5,
    tags: ['pasta', 'fideos', 'espaguetis', 'macarrones'],
  },
  {
    id: 'c-avena',
    name: 'Avena en Hojuelas (Cruda)',
    category: 'Carbohidratos',
    emoji: '🥣',
    defaultServingG: 50,
    defaultServingName: '1 tazón / bowl (50g)',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    tags: ['avena', 'oatmeal', 'desayuno'],
  },
  {
    id: 'c-patata',
    name: 'Patata / Papa Cocida o Asada',
    category: 'Carbohidratos',
    emoji: '🥔',
    defaultServingG: 200,
    defaultServingName: '1 patata mediana (200g)',
    calories: 87,
    protein: 1.9,
    carbs: 20.1,
    fat: 0.1,
    fiber: 1.8,
    tags: ['patata', 'papa', 'saciante'],
  },
  {
    id: 'c-boniato',
    name: 'Boniato / Batata Asada',
    category: 'Carbohidratos',
    emoji: '🍠',
    defaultServingG: 200,
    defaultServingName: '1 unidad (200g)',
    calories: 90,
    protein: 2.0,
    carbs: 20.7,
    fat: 0.2,
    fiber: 3.3,
    tags: ['boniato', 'batata', 'camote'],
  },
  {
    id: 'c-pan-integral',
    name: 'Pan Integral',
    category: 'Carbohidratos',
    emoji: '🍞',
    defaultServingG: 50,
    defaultServingName: '1 rebanada grande (50g)',
    calories: 245,
    protein: 9.0,
    carbs: 45.0,
    fat: 2.5,
    fiber: 6.0,
    tags: ['pan', 'tostada', 'integral'],
  },
  {
    id: 'c-pan-blanco',
    name: 'Pan Blanco / Barra',
    category: 'Carbohidratos',
    emoji: '🥖',
    defaultServingG: 60,
    defaultServingName: '1 trozo de barra (60g)',
    calories: 265,
    protein: 8.5,
    carbs: 52.0,
    fat: 1.8,
    fiber: 2.5,
    tags: ['pan blanco', 'baguette'],
  },
  {
    id: 'c-tortilla-trigo',
    name: 'Tortilla de Trigo / Wrap',
    category: 'Carbohidratos',
    emoji: '🫓',
    defaultServingG: 45,
    defaultServingName: '1 unidad (45g)',
    calories: 300,
    protein: 8.0,
    carbs: 52.0,
    fat: 6.5,
    fiber: 3.0,
    tags: ['tortilla', 'wrap', 'fajita'],
  },
  {
    id: 'c-quinoa',
    name: 'Quinoa Cocida',
    category: 'Carbohidratos',
    emoji: '🥗',
    defaultServingG: 150,
    defaultServingName: '1 plato cocido (150g)',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    tags: ['quinoa', 'superalimento'],
  },
  {
    id: 'c-lentejas',
    name: 'Lentejas Cocidas',
    category: 'Carbohidratos',
    emoji: '🍲',
    defaultServingG: 150,
    defaultServingName: '1 plato cocido (150g)',
    calories: 116,
    protein: 9.0,
    carbs: 20.0,
    fat: 0.4,
    fiber: 7.9,
    tags: ['lentejas', 'legumbres', 'hierro'],
  },
  {
    id: 'c-garbanzos',
    name: 'Garbanzos Cocidos',
    category: 'Carbohidratos',
    emoji: '🧆',
    defaultServingG: 150,
    defaultServingName: '1 plato cocido (150g)',
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    tags: ['garbanzos', 'legumbres'],
  },

  // ── LÁCTEOS Y DERIVADOS ──
  {
    id: 'l-leche-entera',
    name: 'Leche Entera',
    category: 'Lácteos',
    emoji: '🥛',
    defaultServingG: 200,
    defaultServingName: '1 vaso (200ml / 200g)',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    tags: ['leche', 'lacteo'],
  },
  {
    id: 'l-leche-desnatada',
    name: 'Leche Desnatada / 0%',
    category: 'Lácteos',
    emoji: '🥛',
    defaultServingG: 200,
    defaultServingName: '1 vaso (200ml / 200g)',
    calories: 35,
    protein: 3.4,
    carbs: 5.0,
    fat: 0.2,
    tags: ['leche desnatada', 'ligera'],
  },
  {
    id: 'l-yogur-griego',
    name: 'Yogur Griego Natural',
    category: 'Lácteos',
    emoji: '🥣',
    defaultServingG: 125,
    defaultServingName: '1 tarrina (125g)',
    calories: 115,
    protein: 9.0,
    carbs: 4.0,
    fat: 7.0,
    tags: ['yogur griego', 'proteina'],
  },
  {
    id: 'l-queso-batido',
    name: 'Queso Fresco Batido 0%',
    category: 'Lácteos',
    emoji: '🧀',
    defaultServingG: 150,
    defaultServingName: '1 ración (150g)',
    calories: 52,
    protein: 10.0,
    carbs: 3.5,
    fat: 0.1,
    tags: ['queso batido', 'quark', '0%', 'alta proteina'],
  },
  {
    id: 'l-cottage',
    name: 'Queso Cottage',
    category: 'Lácteos',
    emoji: '🧀',
    defaultServingG: 100,
    defaultServingName: '1 ración (100g)',
    calories: 98,
    protein: 11.0,
    carbs: 3.4,
    fat: 4.3,
    tags: ['cottage', 'queso'],
  },
  {
    id: 'l-mozzarella',
    name: 'Queso Mozzarella',
    category: 'Lácteos',
    emoji: '🍕',
    defaultServingG: 50,
    defaultServingName: '1 porción (50g)',
    calories: 280,
    protein: 22.0,
    carbs: 2.0,
    fat: 21.0,
    tags: ['mozzarella', 'queso'],
  },
  {
    id: 'l-bebida-soja',
    name: 'Bebida de Soja sin azúcar',
    category: 'Lácteos',
    emoji: '🌱',
    defaultServingG: 200,
    defaultServingName: '1 vaso (200ml / 200g)',
    calories: 38,
    protein: 3.3,
    carbs: 1.0,
    fat: 2.0,
    tags: ['soja', 'vegetal', 'sin azucar'],
  },

  // ── GRASAS Y FRUTOS SECOS ──
  {
    id: 'g-aove',
    name: 'Aceite de Oliva Virgen Extra (AOVE)',
    category: 'Grasas & Frutos Secos',
    emoji: '🫒',
    defaultServingG: 10,
    defaultServingName: '1 cucharada sopera (10g)',
    calories: 884,
    protein: 0.0,
    carbs: 0.0,
    fat: 100.0,
    tags: ['aceite', 'oliva', 'aove', 'grasa saludable'],
  },
  {
    id: 'g-mantequilla-cacahuete',
    name: 'Crema de Cacahuete / Maní 100%',
    category: 'Grasas & Frutos Secos',
    emoji: '🥜',
    defaultServingG: 20,
    defaultServingName: '1 cucharada (20g)',
    calories: 588,
    protein: 25.0,
    carbs: 20.0,
    fat: 50.0,
    fiber: 8.0,
    tags: ['crema cacahuete', 'peanut butter', 'energia'],
  },
  {
    id: 'g-almendras',
    name: 'Almendras Naturales / Tostadas',
    category: 'Grasas & Frutos Secos',
    emoji: '🌰',
    defaultServingG: 30,
    defaultServingName: '1 puñado (30g)',
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    tags: ['almendras', 'fruto seco', 'magnesio'],
  },
  {
    id: 'g-nueces',
    name: 'Nueces',
    category: 'Grasas & Frutos Secos',
    emoji: '🥜',
    defaultServingG: 30,
    defaultServingName: '5 nueces enteras (30g)',
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    tags: ['nueces', 'omega 3'],
  },
  {
    id: 'g-anacardos',
    name: 'Anacardos / Castañas de Cajú',
    category: 'Grasas & Frutos Secos',
    emoji: '🥜',
    defaultServingG: 30,
    defaultServingName: '1 puñado (30g)',
    calories: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.8,
    fiber: 3.3,
    tags: ['anacardos', 'caju'],
  },
  {
    id: 'g-chocolate-85',
    name: 'Chocolate Negro 85%',
    category: 'Grasas & Frutos Secos',
    emoji: '🍫',
    defaultServingG: 20,
    defaultServingName: '2 onzas (20g)',
    calories: 580,
    protein: 8.5,
    carbs: 20.0,
    fat: 48.0,
    fiber: 11.0,
    tags: ['chocolate', 'antioxidantes'],
  },

  // ── VERDURAS Y HORTALIZAS ──
  {
    id: 'v-espinacas',
    name: 'Espinacas Frescas',
    category: 'Verduras',
    emoji: '🥬',
    defaultServingG: 100,
    defaultServingName: '1 bol de ensalada (100g)',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    tags: ['espinacas', 'hoja verde', 'hierro'],
  },
  {
    id: 'v-brocoli',
    name: 'Brócoli al Vapor / Cocido',
    category: 'Verduras',
    emoji: '🥦',
    defaultServingG: 150,
    defaultServingName: '1 ración (150g)',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    tags: ['brocoli', 'verdura', 'fibra'],
  },
  {
    id: 'v-tomate',
    name: 'Tomate Ensalada',
    category: 'Verduras',
    emoji: '🍅',
    defaultServingG: 150,
    defaultServingName: '1 tomate mediano (150g)',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    tags: ['tomate', 'ensalada'],
  },
  {
    id: 'v-lechuga',
    name: 'Lechuga / Mezclum',
    category: 'Verduras',
    emoji: '🥗',
    defaultServingG: 80,
    defaultServingName: '1 bol (80g)',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    tags: ['lechuga', 'ensalada'],
  },
  {
    id: 'v-zanahoria',
    name: 'Zanahoria Cruda / Cocida',
    category: 'Verduras',
    emoji: '🥕',
    defaultServingG: 100,
    defaultServingName: '1 zanahoria mediana (100g)',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    tags: ['zanahoria', 'vitamina a'],
  },
  {
    id: 'v-champinones',
    name: 'Champiñones / Setas a la Plancha',
    category: 'Verduras',
    emoji: '🍄',
    defaultServingG: 100,
    defaultServingName: '1 ración (100g)',
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1.0,
    tags: ['champinones', 'setas'],
  },
  {
    id: 'v-calabacin',
    name: 'Calabacín a la Plancha',
    category: 'Verduras',
    emoji: '🥒',
    defaultServingG: 150,
    defaultServingName: '1 unidad mediana (150g)',
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1.0,
    tags: ['calabacin', 'zucchini'],
  },
  {
    id: 'v-pimiento',
    name: 'Pimiento Rojo / Verde',
    category: 'Verduras',
    emoji: '🫑',
    defaultServingG: 100,
    defaultServingName: '1/2 pimiento (100g)',
    calories: 31,
    protein: 1.0,
    carbs: 6.0,
    fat: 0.3,
    fiber: 2.1,
    tags: ['pimiento'],
  },
  {
    id: 'v-cebolla',
    name: 'Cebolla',
    category: 'Verduras',
    emoji: '🧅',
    defaultServingG: 80,
    defaultServingName: '1/2 cebolla (80g)',
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    tags: ['cebolla'],
  },
]
