import { Platform, TextStyle } from 'react-native'

export const typography = {
  fontFamily: {
    regular: Platform.select({ ios: 'System', default: 'sans-serif' }),
    medium: Platform.select({ ios: 'System', default: 'sans-serif-medium' }),
    semiBold: Platform.select({ ios: 'System', default: 'sans-serif-medium' }),
    bold: Platform.select({ ios: 'System', default: 'sans-serif' }),
    extraBold: Platform.select({ ios: 'System', default: 'sans-serif' }),
  },
  greeting: {
    fontSize: 24,
    fontWeight: '700' as const,
    lineHeight: 28,
    letterSpacing: -0.6,
    color: '#FAFAFA',
  } satisfies TextStyle,
  headerDate: {
    fontSize: 13,
    fontWeight: '400' as const,
    lineHeight: 16,
    letterSpacing: -0.1,
    color: '#71717A',
  } satisfies TextStyle,
  heroMetric: {
    fontSize: 38,
    fontWeight: '800' as const,
    lineHeight: 42,
    letterSpacing: -1.2,
    fontVariant: ['tabular-nums'] as TextStyle['fontVariant'],
    color: '#FAFAFA',
  } satisfies TextStyle,
  readinessTitle: {
    fontSize: 13,
    fontWeight: '500' as const,
    letterSpacing: -0.2,
    color: '#A1A1AA',
  } satisfies TextStyle,
  readinessSubStatus: {
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0,
    color: '#A1A1AA',
  } satisfies TextStyle,
  badgeText: {
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.2,
    color: '#D4D4D8',
  } satisfies TextStyle,
  workoutEyebrow: {
    fontSize: 12,
    fontWeight: '600' as const,
    letterSpacing: -0.2,
    color: '#52525B',
  } satisfies TextStyle,
  workoutTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    lineHeight: 26,
    letterSpacing: -0.5,
    color: '#09090B',
  } satisfies TextStyle,
  workoutMeta: {
    fontSize: 13,
    fontWeight: '500' as const,
    letterSpacing: -0.1,
    color: '#52525B',
  } satisfies TextStyle,
  buttonText: {
    fontSize: 12,
    fontWeight: '800' as const,
    letterSpacing: 0.8,
    color: '#09090B',
  } satisfies TextStyle,
  cardTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    lineHeight: 20,
    letterSpacing: -0.3,
    color: '#FAFAFA',
  } satisfies TextStyle,
  macroValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
    fontVariant: ['tabular-nums'] as TextStyle['fontVariant'],
    color: '#FAFAFA',
  } satisfies TextStyle,
  macroLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    lineHeight: 14,
    letterSpacing: -0.1,
    color: '#E4E4E7',
  } satisfies TextStyle,
  captionMuted: {
    fontSize: 11,
    fontWeight: '400' as const,
    lineHeight: 13,
    color: '#71717A',
  } satisfies TextStyle,
  calorieLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: '#A1A1AA',
    fontVariant: ['tabular-nums'] as TextStyle['fontVariant'],
  } satisfies TextStyle,
  calorieValue: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: '#A3E635',
    fontVariant: ['tabular-nums'] as TextStyle['fontVariant'],
  } satisfies TextStyle,
  navLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
    lineHeight: 12,
    letterSpacing: 0.2,
  } satisfies TextStyle,
} as const
